import React from "react";

function DeforestationAssessmentReport() {
  const ReportTitle = ({ title, subtitle }: { title: string; subtitle?: string }) => (
    <div className="text-center mb-6">
      <h1 className="text-xl font-bold uppercase tracking-wide">{title}</h1>
      {subtitle && <p className="mt-1 text-sm font-medium">{subtitle}</p>}
    </div>
  );

  const InfoGrid = ({ data }: { data: Record<string, string> }) => (
    <div className="grid grid-cols-2 gap-y-1">
      {Object.entries(data).map(([label, value], idx) => (
        <React.Fragment key={idx}>
          <p>{label}</p>
          <p className="font-medium">{value}</p>
        </React.Fragment>
      ))}
    </div>
  );

  const FarmStatusTable = () => {
    const rows = [
      {
        name: "Mary’s Farm",
        geolocation: "1.234567, 32.567890\n1.234567, 32.567890",
        address: "Kampala",
        status: "Deforestation-free",
        date: "Nov 30, 2026",
        danger: false,
      },
      {
        name: "Mary’s Farm",
        geolocation: "1.234567, 32.567890\n1.234567, 32.567890",
        address: "Kampala",
        status: "Deforestation-free",
        date: "Nov 30, 2026",
        danger: false,
      },
      {
        name: "Mary’s Farm",
        geolocation: "1.234567, 32.567890\n1.234567, 32.567890",
        address: "Kampala",
        status: "Affected",
        date: "Nov 30, 2026",
        danger: true,
      },
    ];

    return (
      <table className="w-full text-xs border mt-2">
        <thead>
          <tr className="bg-[#F4F4F5] text-left text-[#0F2A38]">
            <th className="border px-3 py-1">Farm name</th>
            <th className="border px-3 py-1">Farm geolocation</th>
            <th className="border px-3 py-1">Address</th>
            <th className="border px-3 py-1">Deforestation status</th>
            <th className="border px-3 py-1">Last checked</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i}>
              <td className="border px-3 py-1">{r.name}</td>
              <td className="border px-3 py-1 whitespace-pre-wrap">
                {r.geolocation}
              </td>
              <td className="border px-3 py-1">{r.address}</td>
              <td
                className={`border px-3 py-1 font-semibold ${
                  r.danger ? "text-red-600" : "text-green-700"
                }`}
              >
                {r.status}
              </td>
              <td className="border px-3 py-1">{r.date}</td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  return (
    <div
      id="deforestation-report-pdf"
      className="w-[595px] h-[842px] px-10 py-12 bg-white text-[#0F2A38] text-sm font-sans"
    >
      {/* Title */}
      <ReportTitle
        title="Deforestation Assessment Report"
        subtitle="for consignment CONS-248-X89"
      />

      {/* Section A */}
      <section className="mt-6">
        <h2 className="font-semibold mb-2">A. Operator Info</h2>
        <InfoGrid
          data={{
            "User ID": "UI89",
            Name: "Coffee World Exporters Ltd",
            Address: "Nakawa, Kampala, Uganda",
            Email: "coffeewld@gmail.com",
            "UCDA Export permit number": "UCDA/EXP/0653/2025",
          }}
        />
      </section>

      {/* Section B */}
      <section className="mt-6">
        <h2 className="font-semibold mb-2">B. Consignment Overview</h2>
        <InfoGrid
          data={{
            "Consignment ID": "CONS-248-X89",
            "Product type": "Green Coffee beans",
            "HS Code": "0901.11 – Coffee, not roasted, not decaffeinated",
            "Trade Name": "Uganda Robusta, Screen 16",
            "Export Volume": "4000kg",
            "Country of production": "Uganda",
            "Destination country": "Rotterdam, Netherlands",
            "Export date": "May 3, 2027",
            Batches: "4000",
            "Shipping details":
              "Container #ABC123, Via Mombasa, Vessel: MSC Eagle",
          }}
        />
      </section>

      {/* Section C */}
      <section className="mt-6">
        <h2 className="font-semibold mb-2">C. Deforestation status</h2>
        <p>
          Country of production: <span className="font-medium">Uganda</span>
        </p>
        <p>
          Farms: <span className="font-medium">80</span>
        </p>
        <FarmStatusTable />
      </section>

      {/* Footer */}
      <p className="text-xs text-center text-gray-500 italic mt-6">
        Generated by Coffichain Traceability Solution
      </p>
    </div>
  );
}

export default DeforestationAssessmentReport;
